name: Quality

on:
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-3
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-3
      - name: Install dependencies
        run: npm ci
      - name: Unit test
        run: npm run test
